# scripts/generate_email.py
# Convert the markdown digest (generated by generate_digest.py) into
# HTML email + plain-text fallback.  Pure format conversion — no logic.

import re
import html as html_mod
from pathlib import Path
from datetime import date

DIGEST_DIR = Path("digests")

DIGEST_DIR.mkdir(exist_ok=True)

# ---------------------------------------------------------------------------
# HTML style constants (inline for email client compatibility)
# ---------------------------------------------------------------------------

PAGE_STYLE = (
    "max-width:640px;margin:0 auto;font-family:-apple-system,BlinkMacSystemFont,"
    '"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;'
    "color:#1a1a2e;line-height:1.7;background:#fafafa;"
)
HEADER_STYLE = (
    "background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);"
    "color:#fff;padding:40px 32px;text-align:center;border-radius:8px 8px 0 0;"
)
TITLE_STYLE = "font-size:28px;font-weight:700;margin:0 0 8px;letter-spacing:-0.5px;"
DATE_STYLE = "font-size:14px;opacity:0.75;margin:0;"
BODY_STYLE = "background:#fff;padding:32px;border-radius:0 0 8px 8px;"
HIGHLIGHT_STYLE = (
    "background:#f0f4ff;border-left:4px solid #4a6cf7;"
    "padding:20px 24px;margin:0 0 32px;border-radius:0 6px 6px 0;"
    "font-size:15px;color:#333;line-height:1.8;"
)
CARD_STYLE = (
    "border:1px solid #e8ecf1;border-radius:8px;padding:24px;margin-bottom:20px;"
    "background:#fff;"
)
CARD_TITLE_STYLE = "font-size:18px;font-weight:700;margin:0 0 4px;"
CARD_LINK_STYLE = "color:#4a6cf7;text-decoration:none;"
CARD_META_STYLE = "font-size:13px;color:#888;margin:0 0 16px;"
SECTION_LABEL_STYLE = (
    "font-size:12px;font-weight:600;text-transform:uppercase;"
    "letter-spacing:0.5px;color:#4a6cf7;margin:0 0 6px;"
)
SECTION_TEXT_STYLE = "font-size:14px;color:#444;margin:0;line-height:1.8;"
FOOTER_STYLE = (
    "text-align:center;padding:24px 32px;font-size:12px;color:#999;line-height:1.6;"
)

# ---------------------------------------------------------------------------
# Markdown → HTML converter
# ---------------------------------------------------------------------------

def md_to_html(md_text: str) -> str:
    """Convert our specific markdown format into HTML email body."""
    lines = md_text.strip().split("\n")
    html_parts = []
    i = 0

    while i < len(lines):
        line = lines[i]

        # --- H1: # Daily Digest (date) ---
        if line.startswith("# "):
            # Handled in build_html_page — skip
            i += 1
            continue

        # --- Blockquote: > overall highlight ---
        if line.startswith("> "):
            text = line[2:].strip()
            html_parts.append(
                f'<div style="{HIGHLIGHT_STYLE}">'
                f'<p style="margin:0;">{html_mod.escape(text)}</p>'
                f'</div>'
            )
            i += 1
            continue

        # --- Horizontal rule: start of a story card ---
        if line.strip() == "---":
            i += 1
            # Collect everything until next --- or end
            card_lines = []
            while i < len(lines) and lines[i].strip() != "---":
                card_lines.append(lines[i])
                i += 1
            html_parts.append(_build_story_card_html(card_lines))
            continue

        i += 1

    return "\n".join(html_parts)


def _build_story_card_html(lines: list[str]) -> str:
    """Parse a single story block and return its HTML card."""
    if not lines:
        return ""

    title_line = ""
    meta_line = ""
    sections: list[tuple[str, list[str]]] = []  # (label, content_lines)

    i = 0
    # --- Title: ## N. [Title](url) ---
    if i < len(lines) and lines[i].startswith("## "):
        title_line = lines[i][3:].strip()
        i += 1

    # Defensive: skip if no title found (e.g. trailing separator, footer)
    if not title_line:
        return ""

    # Skip blank lines
    while i < len(lines) and not lines[i].strip():
        i += 1

    # --- Meta: ⬆ **score** points · 💬 **comments** comments ---
    if i < len(lines) and ("points" in lines[i] or "comments" in lines[i]):
        meta_line = lines[i].strip()
        i += 1
        # Skip blank
        while i < len(lines) and not lines[i].strip():
            i += 1

    # --- Sections: ### heading + paragraph ---
    while i < len(lines):
        if lines[i].startswith("### "):
            label = lines[i][4:].strip()
            i += 1
            content_lines = []
            while i < len(lines) and not lines[i].startswith("### ") and not lines[i].startswith("## "):
                if lines[i].strip():
                    content_lines.append(lines[i].strip())
                i += 1
            sections.append((label, content_lines))
        else:
            i += 1

    # --- Build HTML ---
    # Parse title with markdown link:  N. [text](url)
    # Greedy (.+) for URL correctly captures the last ) as the markdown closing paren
    link_match = re.match(r'^(\d+)\.\s*\[(.+)\]\((.+)\)$', title_line)
    if link_match:
        num = link_match.group(1)
        text = html_mod.escape(link_match.group(2))
        url = html_mod.escape(link_match.group(3))
        title_html = f'{num}. <a href="{url}" style="{CARD_LINK_STYLE}" target="_blank">{text}</a>'
    else:
        title_html = html_mod.escape(title_line)

    # Parse meta line: strip markdown bold markers
    meta_html = html_mod.escape(meta_line.replace("**", ""))

    # Build sections
    section_blocks = []
    for label, content_lines in sections:
        label_html = html_mod.escape(label)
        content_html = "<br>".join(html_mod.escape(cl) for cl in content_lines)
        section_blocks.append(
            f'<div style="{SECTION_LABEL_STYLE}">{label_html}</div>'
            f'<p style="{SECTION_TEXT_STYLE}">{content_html}</p>'
        )

    sections_html = "\n".join(section_blocks)

    return (
        f'<div style="{CARD_STYLE}">'
        f'<h2 style="{CARD_TITLE_STYLE}">{title_html}</h2>'
        f'<p style="{CARD_META_STYLE}">{meta_html}</p>'
        f'{sections_html}'
        f'</div>'
    )


# ---------------------------------------------------------------------------
# Page assembly
# ---------------------------------------------------------------------------

def build_html_page(md_text: str, today: str) -> str:
    """Wrap the converted HTML body into a full email page."""
    body_html = md_to_html(md_text)

    return f"""\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body style="margin:0;padding:20px;background:#f0f2f5;">
<table style="{PAGE_STYLE}" cellpadding="0" cellspacing="0" role="presentation">
  <tr><td>
    <div style="{HEADER_STYLE}">
      <h1 style="{TITLE_STYLE}">📰 Daily Digest</h1>
      <p style="{DATE_STYLE}">{today}</p>
    </div>
    <div style="{BODY_STYLE}">
      {body_html}
    </div>
    <div style="{FOOTER_STYLE}">
      <p style="margin:0;">由 DeepSeek 自动生成 · Hacker News Top 10 摘要</p>
      <p style="margin:4px 0 0;">Generated by Daily Digest</p>
    </div>
  </td></tr>
</table>
</body>
</html>"""


def md_to_plain(md_text: str) -> str:
    """Strip markdown formatting for plain-text email fallback."""
    # Remove link syntax: [text](url) → text (url)
    text = re.sub(r'\[([^\]]+)\]\(([^)]+)\)', r'\1 (\2)', md_text)
    # Remove bold markers
    text = text.replace("**", "")
    return text


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    today = date.today().isoformat()
    md_file = DIGEST_DIR / f"{today}.md"

    if not md_file.exists():
        raise FileNotFoundError(
            f"{md_file} not found. Run generate_digest.py first."
        )

    md_content = md_file.read_text(encoding="utf-8")

    # --- HTML ---
    html_output = build_html_page(md_content, today)
    html_file = DIGEST_DIR / f"{today}.html"
    html_file.write_text(html_output, encoding="utf-8")
    print(f"HTML email → {html_file}")

    # --- Plain text ---
    txt_output = md_to_plain(md_content)
    txt_file = DIGEST_DIR / f"{today}.txt"
    txt_file.write_text(txt_output, encoding="utf-8")
    print(f"Plain text  → {txt_file}")


if __name__ == "__main__":
    main()
