# scripts/send_email.py
# Read enriched news JSON, build HTML + plain-text email, and send via SMTP.
# No intermediate files — the email HTML never touches digests/.

import json
import os
import smtplib
import html as html_mod
from pathlib import Path
from datetime import date
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

DATA_DIR = Path("data")
ENRICHED_FILE = DATA_DIR / "enriched_news.json"


# ---------------------------------------------------------------------------
# HTML style (inline for email client compatibility)
# ---------------------------------------------------------------------------
PAGE_STYLE = (
    "max-width:640px;margin:0 auto;font-family:-apple-system,BlinkMacSystemFont,"
    '"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;'
    "color:#1a1a2e;line-height:1.7;background:#fafafa;"
)
HEADER_STYLE = (
    "background:linear-gradient(135deg,#1a1a2e 0%,#16213e 100%);"
    "color:#fff;padding:40px 32px;text-align:center;border-radius:8px 8px 0 0;"
)
TITLE_STYLE = "font-size:28px;font-weight:700;margin:0 0 8px;letter-spacing:-0.5px;"
DATE_STYLE = "font-size:14px;opacity:0.75;margin:0;"
BODY_STYLE = "background:#fff;padding:32px;border-radius:0 0 8px 8px;"
HIGHLIGHT_STYLE = (
    "background:#f0f4ff;border-left:4px solid #4a6cf7;"
    "padding:20px 24px;margin:0 0 32px;border-radius:0 6px 6px 0;"
    "font-size:15px;color:#333;line-height:1.8;"
)
CARD_STYLE = (
    "border:1px solid #e8ecf1;border-radius:8px;padding:24px;margin-bottom:20px;"
    "background:#fff;"
)
CARD_TITLE_STYLE = "font-size:18px;font-weight:700;margin:0 0 4px;"
CARD_LINK_STYLE = "color:#4a6cf7;text-decoration:none;"
CARD_META_STYLE = "font-size:13px;color:#888;margin:0 0 16px;"
SECTION_LABEL_STYLE = (
    "font-size:12px;font-weight:600;"
    "letter-spacing:0.5px;color:#4a6cf7;margin:0 0 6px;"
)
SECTION_TEXT_STYLE = "font-size:14px;color:#444;margin:0;line-height:1.8;"
DIVIDER_STYLE = "border:none;border-top:1px solid #e8ecf1;margin:12px 0;"
FOOTER_STYLE = (
    "text-align:center;padding:24px 32px;font-size:12px;color:#999;line-height:1.6;"
)


# ---------------------------------------------------------------------------
# Build HTML from enriched JSON (no markdown parsing needed)
# ---------------------------------------------------------------------------

def build_html(data: dict) -> str:
    today = data.get("date", date.today().isoformat())
    overall = data.get("overall_highlight", "")
    stories = data.get("stories", [])
    model = data.get("model", "DeepSeek")

    # --- Highlight ---
    highlight_html = ""
    if overall:
        highlight_html = (
            f'<div style="{HIGHLIGHT_STYLE}">'
            f'<p style="margin:0;">{html_mod.escape(overall)}</p>'
            f'</div>'
        )

    # --- Story cards ---
    cards_html = "\n".join(_build_card(s) for s in stories)

    body_html = f"{highlight_html}\n{cards_html}" if cards_html else highlight_html

    return f"""\
<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
</head>
<body style="margin:0;padding:20px;background:#f0f2f5;">
<table style="{PAGE_STYLE}" cellpadding="0" cellspacing="0" role="presentation">
  <tr><td>
    <div style="{HEADER_STYLE}">
      <h1 style="{TITLE_STYLE}">📰 Daily Digest</h1>
      <p style="{DATE_STYLE}">{today}</p>
    </div>
    <div style="{BODY_STYLE}">
      {body_html}
    </div>
    <div style="{FOOTER_STYLE}">
      <p style="margin:0;">由 {html_mod.escape(model)} 自动生成 · 多源科技新闻摘要</p>
      <p style="margin:4px 0 0;">Generated by Daily Digest</p>
    </div>
  </td></tr>
</table>
</body>
</html>"""


def _build_card(story: dict) -> str:
    rank = story["rank"]
    title = html_mod.escape(story["title"])
    url = story.get("url", "")
    source = story.get("source", "")
    score = story.get("score", 0)
    descendants = story.get("descendants", 0)
    article_concepts = story.get("article_concepts", "")
    article_background = story.get("article_background", "")
    article_summary = story.get("article_summary", "")
    comment_summary = story.get("comment_summary", "")

    # Title: linked if URL present, plain text otherwise
    if url:
        title_html = (
            f'{rank}. '
            f'<a href="{html_mod.escape(url)}" style="{CARD_LINK_STYLE}" target="_blank">'
            f'{title}</a>'
        )
    else:
        title_html = f"{rank}. {title}"

    meta_parts = [f"来源：{html_mod.escape(source)}"] if source else []
    if score:
        meta_parts.append(f"⬆ {score} points")
    if descendants:
        meta_parts.append(f"💬 {descendants} comments")
    meta_html = " · ".join(meta_parts)

    # Sections: concepts -> background -> summary -> comments
    sections = []
    if article_concepts:
        sections.append(
            f'<div style="{SECTION_LABEL_STYLE}">🔑 关键概念</div>'
            f'<p style="{SECTION_TEXT_STYLE};white-space:pre-line;">{html_mod.escape(article_concepts)}</p>'
        )
    if article_background:
        sections.append(
            f'<div style="{SECTION_LABEL_STYLE}">🔍 背景</div>'
            f'<p style="{SECTION_TEXT_STYLE}">{html_mod.escape(article_background)}</p>'
        )
    if article_summary:
        sections.append(
            f'<div style="{SECTION_LABEL_STYLE}">📝 文章摘要</div>'
            f'<p style="{SECTION_TEXT_STYLE}">{html_mod.escape(article_summary)}</p>'
        )
    if comment_summary:
        sections.append(
            f'<div style="{SECTION_LABEL_STYLE}">💬 社区讨论</div>'
            f'<p style="{SECTION_TEXT_STYLE}">{html_mod.escape(comment_summary)}</p>'
        )

    divider = f'<hr style="{DIVIDER_STYLE}">' if len(sections) > 1 else ""
    sections_html = divider.join(sections)

    return (
        f'<div style="{CARD_STYLE}">'
        f'<h2 style="{CARD_TITLE_STYLE}">{title_html}</h2>'
        f'<p style="{CARD_META_STYLE}">{meta_html}</p>'
        f'{sections_html}'
        f'</div>'
    )


# ---------------------------------------------------------------------------
# Plain text fallback
# ---------------------------------------------------------------------------

def build_plain(data: dict) -> str:
    today = data.get("date", date.today().isoformat())
    overall = data.get("overall_highlight", "")
    stories = data.get("stories", [])

    lines = [f"Daily Digest — {today}", "", "=" * 40, ""]
    if overall:
        lines.append(overall)
        lines.append("")

    for s in stories:
        lines.append(f"{s['rank']}. {s['title']}")
        if s.get("url"):
            lines.append(f"   {s['url']}")
        meta = []
        if s.get("source"):
            meta.append(f"Source: {s['source']}")
        if s.get("score"):
            meta.append(f"Score: {s['score']}")
        if s.get("descendants"):
            meta.append(f"Comments: {s.get('descendants', 0)}")
        if meta:
            lines.append(f"   {' | '.join(meta)}")
        if s.get("article_concepts"):
            lines.append(f"   🔑 {s['article_concepts']}")
        if s.get("article_background"):
            lines.append(f"   🔍 {s['article_background']}")
        if s.get("article_summary"):
            lines.append(f"   📝 {s['article_summary']}")
        if s.get("comment_summary"):
            lines.append(f"   💬 {s['comment_summary']}")
        lines.append("")

    lines.append("— Generated by Daily Digest Bot")
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    today = date.today().isoformat()

    with open(ENRICHED_FILE, encoding="utf-8") as f:
        data = json.load(f)

    # Build email parts directly from JSON — no intermediate files
    html_content = build_html(data)
    txt_content = build_plain(data)

    # Multipart message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Daily Digest — {today}"
    msg["From"] = os.environ["EMAIL_USER"]
    msg["To"] = os.environ["EMAIL_TO"]

    msg.attach(MIMEText(txt_content, "plain", "utf-8"))
    msg.attach(MIMEText(html_content, "html", "utf-8"))

    with smtplib.SMTP_SSL("smtp.gmail.com", 465) as server:
        server.login(
            os.environ["EMAIL_USER"],
            os.environ["EMAIL_PASSWORD"],
        )
        server.send_message(msg)

    print(f"Email sent to {os.environ['EMAIL_TO']}")


if __name__ == "__main__":
    main()
